apiVersion: v1
kind: Service
metadata:
  name: factorial-web
  labels:
    app: factorial-web
spec:
  selector:
    app: factorial-web
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
  scale:
    replicas: 2
    minReplicas: 1
    maxReplicas: 5
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: |
      [
        {
          "type": "AveragedCPUUtilization",
          "value": 80,
          "periodSeconds": 60
        },
        {
          "type": "AveragedMemoryUtilization",
          "value": 80,
          "periodSeconds": 60
        }
      ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: factorial-web
  labels:
    app: factorial-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: factorial-web
  template:
    metadata:
      labels:
        app: factorial-web
    spec:
      containers:
        - name: factorial-web
          image: mrcolorrain/factorialwww:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
